# Generated by Django 5.1.1 on 2024-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fitplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='progresso/')),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Medida',
        ),
    ]
